apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: planmaster # Es buena práctica usar un namespace dedicado
type: Opaque
data:
  db-user: d2FsbGV0X2FkbWRi # Reemplaza con tu base64
  db-password: dzRsbDN0REI= # Reemplaza con tu base64